# Generated by Django 3.2.14 on 2022-07-15 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 14, 36, 52, 804970, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
